name: mimic-pipeline
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - numpy
  - xgboost
  - tqdm
  - scikit-learn
  - ipywidgets
  - imbalanced-learn
  - pytorch
  - nltk
  - requests
  - pip
  - pip:
      - import-ipynb
      - captum
      - pytorch_pretrained_bert
      - PyRush
      - torchvision
      - wfdb
      - transformers
      - pydicom